[package]
name = "vangers-srv-shell"
version = "0.1.0"
authors = ["Vitaliy Busko <vitaliy.opensource@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vangers-srv = { path = "../vangers-srv" }
